
version: 2

sources:
  - name: world_unicorns
    schema: public
    tables:
      - name: unicorn_companies
      - name: unicorn_funding
      - name: unicorn_dates
      - name: unicorn_industries

# models:
#   - name: my_first_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null

#   - name: my_second_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null
